### ISSUE TITLE
Scripts needed to generate the executables

### ISSUE THREAD

**Issue by me-kell** [me-kell/EXMARaLDA-build#2]
The executable "PartiturEditorWithFOBS.exe" in FobsJMF seems to be a Java executable wrapper generated by JSmooth http://jsmooth.sourceforge.net/
Can we have the script and include it in the build process?
Same issue for the other executables.

**Comment by berndmoos** [comment]
Here goes:

[jsmooth.zip](https://github.com/me-kell/EXMARaLDA-build/files/1209343/jsmooth.zip)
