### ISSUE TITLE
How to bind the JDS Player via java.library.path

### ISSUE THREAD

**Issue by me-kell** [me-kell/EXMARaLDA-build#5]
How to bind the JDS Player via java.library.path.

**Comment by berndmoos** [comment]
EXMARaLDA on Windows requires the following native libraries:

- DSPlayer.dll (for the JDS player)
- fobs4jmf.dll (for the FOBS JMF player)
- MMFPlayer.dll (for the MMF player)

These are provided by the MPI Nijmegen as part of ELAN, the sources (last time I looked) are not available.

In the EXMARaLDA distributions, the native libraries are placed inside the /bin folder of the embedded JRE, so there is no need to set an explicit java.library.path. Putting them elsewhere and setting the library path accordingly might work, too.
