### ISSUE TITLE
Icons in EXMARaLDA installation

### ISSUE THREAD

**Issue by me-kell** [me-kell/EXMARaLDA-build#6]
In an EXMARaLDA installation there are different icons. Do we need them? Or can we move them to the jar as resources? 
```
  ./coma.ico
  ./comadocument.ico
  ./exakt.ico
  ./exmaralda.ico
  ./exmaralda_install.ico
  ./folker-document-icon-128.ico
  ./folker.ico
  ./orthonormal.ico
  ./partitureditor.ico
  ./pe-document-icon.ico
  ./segmented_document.ico
  ./sextant-document.ico
  ./sextant.ico
  ./surfer.ico
  ./teidropicon.ico
```

**Comment by berndmoos** [comment]
As far as I remember, these are the icons that Windows (via InnoSetup) will use to display the applications/documents on OS level. Not sure if it is possible to keep those in a jar.
