### ISSUE TITLE
Document origin of jar-artifacts

### ISSUE THREAD

**Issue by me-kell** [me-kell/EXMARaLDA-build#7]
To document the origin of the used jars we wrote a report under [artifacts-report.md](https://github.com/me-kell/EXMARaLDA-build/blob/master/artifacts-report.md). Could someone take a look at it and complete the missing informations?

**Comment by berndmoos** [comment]
I need to find the time to look at this closely. Meanwhile, here is our own feeble attempt to bring some order to the libraries:

https://docs.google.com/spreadsheets/d/1Z9ijcYov67RuShotjREw81T1q_DqXlCc7hSZZ4FNWLc/edit?usp=sharing

The attempt was abandoned some time ago, but maybe there is some useful info in it.

**Comment by berndmoos** [comment]
See here for sources of BAS (=ipsk.jar):

http://www.bas.uni-muenchen.de/Bas/software/source/

But beware: we are using an older version of the code since we found that it worked better than the new version. The sources for the older version seem to be gone...

**Comment by berndmoos** [comment]
Re: AppleJavaExtensions.jar is of unknown origin. 

This is part of Apple's JRE - no sources available afaik

**Comment by berndmoos** [comment]
jctable.jar is a commercial library, we don't have sources, the company does not seem to exist any more. Unfortunately, it is central to the tool, since it is the GUI component displaying the partitur.

**Comment by me-kell** [comment]
See updated [artifacts-report.md](https://github.com/me-kell/EXMARaLDA-build/blob/master/artifacts-report.md).
