### ISSUE TITLE
What are the following files in FobsJMF directory exactly needed for?

### ISSUE THREAD

**Issue by me-kell** [me-kell/EXMARaLDA-build#8]
What are the following files in FobsJMF directory exactly needed for?

- comfyj.lic
- jniwrap.dll
- jniwrap.lic
- jniwrap64.dll
- libjniwrap.jnilib
- libjniwrap.so

**Comment by berndmoos** [comment]
They were needed for the old ELAN DS player. I don't think they're needed for anything now - they can go.

**Comment by berndmoos** [comment]
Q: What is JMF Registry? JMF 2.1.1 maintains a registry of available plugins, package prefixes and other settings in a file called jmf.properties. This is a binary file and should only be modified using the provided JMFRegistry application. This application is a part of the JMF 2.1.1 jmf.jar file and can be run as "java JMFRegistry". It requires that you have Swing-1.1 in your CLASSPATH (or you can use JDK 1.2 or later).

[http://www.oracle.com/technetwork/java/javase/index-135148.html]
